"""Offline demonstration-generation pipeline for hand-agent BC.

Samples domain-randomized hand-play states via `HandPlayAdapter`, labels
each with `hand_solver.solve_hand_for_ante_clear` (the P(clear)-not-EV
oracle -- see CLAUDE.md "Ante-play (hand/discard) track" for why raw EV is
the wrong objective here), and writes padded `.npz` shards for
behavior-cloning training.

Design decided in a /grilling session (see CLAUDE.md open items):
  - Run once per curriculum stage: pass a `HandPlayConfig` + `stage_name`,
    get one dataset in `{output_dir}/{stage_name}/`. Don't mix stages into
    one pool -- BC training consumes stages as separable units.
  - Workers write their own `.npz` shards independently. No centralized
    collector -- avoids a serialization bottleneck and single point of
    failure for a run that's ~12s/example even after the permutation-search
    speed fix.
  - Seeds are `f"{stage_name}_{global_index:08d}"`, partitioned into fixed
    per-worker index ranges. The seed *set* depends only on
    (stage_name, total_examples), not on how many workers happen to run the
    job -- reruns with a different --num-workers still reproduce the same
    dataset.
  - A solver exception on one sampled state is logged to
    `{stage_dir}/worker_{id}_failures.jsonl` (seed + traceback) and skipped,
    not fatal to the whole run -- deterministic seeding makes a later
    retry-only-failures pass possible once the underlying bug is fixed.
  - Card selection labels are stored as five ascending hand indices, padded
    with -1.  They are deliberately independent of the observation width:
    the Candidate-B decoder consumes this canonical set encoding directly.
"""

from __future__ import annotations

import json
import multiprocessing
import pickle
import sys
import time
import traceback
from collections import Counter
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any, Protocol

import numpy as np

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

_REPO_ROOT = _SCRIPTS_DIR.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from hand_solver import AnteClearChoice, DeckComposition, solve_hand_for_ante_clear  # noqa: E402

from jackdaw.engine.actions import Discard as EngineDiscard  # noqa: E402
from jackdaw.engine.actions import PlayHand as EnginePlayHand  # noqa: E402
from jackdaw.engine.hand_eval import get_hand_eval_flags  # noqa: E402
from jackdaw.env.action_space import ActionType  # noqa: E402
from jackdaw.env.hand_play_adapter import (  # noqa: E402
    HandPlayAdapter,
    HandPlayConfig,
    JokerCountBand,
)
from jackdaw.env.hand_play_gym import (  # noqa: E402
    MAX_CONSUMABLES_V2,
    MAX_JOKERS_V2,
    _check_joker_overfill,
    encode_hand_state_v2,
)
from jackdaw.env.observation import (  # noqa: E402
    D_CONSUMABLE,
    D_JOKER,
)

# v2 = the h1 bump (B2 slice 4): 18-wide hand cards (+3 hand-potential),
# 256-wide global context (+21), trigger-match matrix, joker center-key
# ids, Blueprint/Brainstorm copy-resolution fields, and a REAL consumable
# block. B4's index-set labels make this schema incompatible with v2, so
# it is versioned separately; do NOT mix pre-B4 v2 shards with these.
SCHEMA_VERSION = 3
# Joker width is v2's MAX_JOKERS_V2 (15), imported from hand_play_gym so the
# shard width EXACTLY matches the obs width -- the BC loader does not up-pad
# the joker axis (nor trigger_match's joker axis), so a mismatch here would be
# a silent concat/shape failure at load. See the MAX_JOKERS_V2 rationale.
MAX_LABEL_CARDS = 5
BACK_KEY = "b_red"
STAKE = 1

# ---------------------------------------------------------------------------
# Curriculum stage presets
# ---------------------------------------------------------------------------
#
# One dataset per stage, generated by separate invocations (`--stage <name>`)
# — never one mixed pool. Checked into git so the exact generating
# distribution of any dataset is reproducible months later; CLI flags
# override individual fields when experimenting.

# Count-first weighted joker-count distribution (see JokerCountBand):
# 30% five-joker boards (ante 3+ only), tapering to 10% each for 0/1/2,
# with 0/1-joker states confined to antes 1-2 where they actually occur
# in real play.
DEFAULT_COUNT_BANDS: tuple[JokerCountBand, ...] = (
    JokerCountBand(count=0, weight=0.10, ante_range=(1, 2)),
    JokerCountBand(count=1, weight=0.10, ante_range=(1, 2)),
    JokerCountBand(count=2, weight=0.10),
    JokerCountBand(count=3, weight=0.20),
    JokerCountBand(count=4, weight=0.20),
    JokerCountBand(count=5, weight=0.30, ante_range=(3, 8)),
)

# Stage 2: archetype-spanning curated pool — jokers chosen because they
# visibly CHANGE the optimal play/discard decision, not because they're
# strong. Covers suit/rank/hand-type conditionals, hand-detection modifiers
# (Four Fingers/Shortcut/Splash), order-sensitive scoring (Photograph/
# Hanging Chad/Ancient), scaling accumulation (Ride the Bus/Wee), retrigger
# and held-in-hand effects, plus one decision-irrelevant baseline (Joker).
STAGE2_JOKER_POOL: tuple[str, ...] = (
    "j_joker",
    "j_greedy_joker",
    "j_lusty_joker",
    "j_even_steven",
    "j_odd_todd",
    "j_fibonacci",
    "j_scholar",
    "j_jolly",
    "j_sly",
    "j_crazy",
    "j_droll",
    "j_four_fingers",
    "j_shortcut",
    "j_splash",
    "j_photograph",
    "j_hanging_chad",
    "j_ride_the_bus",
    "j_wee",
    "j_hack",
    "j_raised_fist",
    "j_ancient",
)


def all_joker_keys() -> tuple[str, ...]:
    """Every joker key in the engine's centers.json (150 as of writing)."""
    centers_path = _REPO_ROOT / "jackdaw" / "engine" / "data" / "centers.json"
    with open(centers_path, encoding="utf-8") as f:
        centers = json.load(f)
    return tuple(sorted(k for k in centers if k.startswith("j_")))


@dataclass(frozen=True)
class StagePreset:
    config: HandPlayConfig
    total_examples: int


# Flat hand-size tail for every stage preset (h1 regen config, user-locked
# 2026-07-16): prob 0.1, delta uniform +1..+4 on top of whatever the injected
# jokers produce (additive, so equivalent to bumping base hand size). Its job
# is width-40 / Candidate-B decode-length coverage — the harvest can't supply
# wide hands (see the circular-gate note in HandPlayConfig).
_HAND_SIZE_TAIL = {"hand_size_tail_prob": 0.1, "hand_size_delta_range": (1, 4)}


def stage_presets() -> dict[str, StagePreset]:
    """Named curriculum-stage presets (function, not constant, so the
    all-150 pool is only loaded when actually requested)."""
    return {
        # Pipeline/baseline validation: pure hand-strength play, no jokers.
        "stage1_no_jokers": StagePreset(
            config=HandPlayConfig(**_HAND_SIZE_TAIL),
            total_examples=2_000,
        ),
        # ~4000 x 3.2 avg jokers / 21 pool ~= 610 appearances per joker.
        "stage2_curated": StagePreset(
            config=HandPlayConfig(
                joker_pool=STAGE2_JOKER_POOL,
                joker_count_bands=DEFAULT_COUNT_BANDS,
                **_HAND_SIZE_TAIL,
            ),
            total_examples=4_000,
        ),
        # ~20000 x 3.2 / 150 ~= 425 appearances per joker — marginal
        # embedding exposure, not combinatorial coverage (see CLAUDE.md:
        # BC is a warm start, PPO does the generalization).
        "stage3_full": StagePreset(
            config=HandPlayConfig(
                joker_pool=all_joker_keys(),
                joker_count_bands=DEFAULT_COUNT_BANDS,
                **_HAND_SIZE_TAIL,
            ),
            total_examples=20_000,
        ),
        # Boss-blind-only supplement: stages 1-3 already cover Small/Big
        # broadly, so this stage exists purely to give h0 exposure to boss
        # debuffs (an h0 that's never seen a Boss folds there, distorting
        # every s0 shop value toward "we die anyway" -- see CLAUDE.md). All
        # 150 jokers (same pool as stage3) so boss awareness and full joker
        # coverage compound rather than trading off against each other.
        # 8000 x 1/~24 boss keys ~= 330 appearances per boss -- provisional,
        # same spirit as stage3's marginal-exposure-not-coverage framing.
        "stage4_boss": StagePreset(
            config=HandPlayConfig(
                joker_pool=all_joker_keys(),
                joker_count_bands=DEFAULT_COUNT_BANDS,
                blind_stages=("Boss",),
                **_HAND_SIZE_TAIL,
            ),
            total_examples=8_000,
        ),
    }


def load_dollar_marginals(path: Path) -> dict[int, dict[int, int]]:
    """Parse ``dollar_marginals_by_ante`` from a harvest ``reductions.json``
    (or a bare ``{ante: {dollars: count}}`` mapping). JSON object keys arrive
    as strings; empty per-ante histograms are dropped, and an entirely empty
    table hard-fails rather than silently regenerating with the flat
    placeholder the h1 config retires."""
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    table = raw.get("dollar_marginals_by_ante", raw) if isinstance(raw, dict) else raw
    if not isinstance(table, dict):
        raise ValueError(f"{path}: expected an ante -> dollars -> count mapping")
    marginals = {
        int(ante): {int(dollars): int(count) for dollars, count in hist.items()}
        for ante, hist in table.items()
        if hist
    }
    if not marginals:
        raise ValueError(f"{path}: no non-empty dollar marginals")
    return marginals


class GenerationError(Exception):
    """Raised for a sampled state the pipeline can't turn into a valid
    label -- callers must catch this per-example, not let it kill a
    worker's whole index range."""


@dataclass
class GenerationJobConfig:
    stage_name: str
    hand_play_config: HandPlayConfig
    total_examples: int
    num_workers: int
    output_dir: Path
    shard_size: int = 500


@dataclass
class Example:
    global_context: np.ndarray
    hand_cards: np.ndarray
    hand_mask: np.ndarray
    jokers: np.ndarray
    joker_mask: np.ndarray
    joker_ids: np.ndarray
    copy_active: np.ndarray
    copy_target_ids: np.ndarray
    trigger_match: np.ndarray
    consumables: np.ndarray
    consumable_mask: np.ndarray
    action_type: int
    card_indices: np.ndarray
    p_clear: float
    seed: str


def _pad_1d(arr: np.ndarray, max_n: int, dtype: type) -> np.ndarray:
    out = np.zeros(max_n, dtype=dtype)
    n = min(len(arr), max_n)
    out[:n] = arr[:n]
    return out


def _pad_entities(arr: np.ndarray, max_n: int, dim: int) -> tuple[np.ndarray, np.ndarray]:
    n = arr.shape[0]
    if n > max_n:
        raise GenerationError(f"entity count {n} exceeds max {max_n}")
    padded = np.zeros((max_n, dim), dtype=np.float32)
    mask = np.zeros(max_n, dtype=bool)
    if n > 0:
        padded[:n] = arr
        mask[:n] = True
    return padded, mask


def acted_cards_from_choice(choice: AnteClearChoice) -> list:
    """The cards the label's action actually operates on.

    NOT simply `choice.hold` -- `hold`/`discard` are named from the
    "keep vs. discard" framing of a *discard* decision. For `action=="play"`,
    `hold` is repurposed by `hand_solver.py` to mean "the subset chosen to
    play" (see `best_immediate_play`'s callers), not "cards kept in hand".
    Getting this backwards silently produces a Discard label for what the
    solver actually recommended as a Play, or vice versa.
    """
    if choice.action == "play":
        return choice.hold
    if choice.action == "discard":
        return choice.discard
    raise GenerationError(f"unknown solver action: {choice.action!r}")


def indices_by_identity(cards: list, hand: list) -> list[int]:
    """Map `cards` back to their positions in `hand` by object identity,
    not value equality. `Card` is a plain @dataclass (value-based `__eq__`),
    so an Erratic deck's duplicate-valued cards would otherwise collide
    under `in`/`.index()` -- see the /grilling session and the matching fix
    in `hand_solver.best_immediate_play`.
    """
    id_to_index = {id(c): i for i, c in enumerate(hand)}
    try:
        return [id_to_index[id(c)] for c in cards]
    except KeyError as exc:
        raise GenerationError(
            f"solver returned a card not present (by identity) in the original hand: {exc}"
        ) from exc


class HandTurnState(Protocol):
    """The minimal surface the solve/encode body needs from a hand-turn state.

    Both sources satisfy it: `HandPlayAdapter` (stages 1-4, domain-randomized
    sampling) and `RestoredHarvestState` (stage 5, a restored harvest blob).
    Keeping the body written against this protocol rather than against
    `HandPlayAdapter` is what lets harvested states flow through the EXACT same
    solver, encoder and executability checks -- a second labeling path would be
    a label-divergence surface, which is the bug class this pipeline keeps
    getting bitten by.
    """

    @property
    def raw_state(self) -> dict[str, Any]: ...

    def step(self, action: Any) -> Any: ...


class RestoredHarvestState:
    """A harvested blob, restored, presented as a `HandTurnState`.

    Deliberately thin: it exists only so `label_and_encode` can step the engine
    for tier-2 validation the same way `HandPlayAdapter` does. Restoration and
    capture-skew repair happen in `harvest_restore.restore_state` -- never
    unpickle a harvest blob directly (see that module's docstring).
    """

    def __init__(self, gs: dict[str, Any]) -> None:
        self._gs = gs

    @property
    def raw_state(self) -> dict[str, Any]:
        return self._gs

    def step(self, action: Any) -> dict[str, Any]:
        from jackdaw.engine.game import step as engine_step

        engine_step(self._gs, action)
        return self._gs


def validate_label_executability(
    state: HandTurnState,
    action_type: int,
    selected_indices: list[int],
) -> None:
    """Two-tier guard that a label is executable in the real game. Added
    after the 5-card-discard-cap bug (see CLAUDE.md): 8.3% of the first
    stage-1 dataset labeled discards the engine rejects, and it wasn't
    caught until BC training consumed the shards. Cost is negligible
    against the 2-12s solver call (~10us mask check + ~0.5ms engine step).

    Tier 1: schema-native validation. Indices must be a canonical ascending
    set of 1--5 positions within this state's actual hand length, and the
    action's hand/discard budget must remain. This intentionally does not
    route through the old fixed-width Discrete(436) action space: doing so
    silently rejected every label touching position 8 or later.

    Tier 2: actually execute the action through the real engine. This is
    DESTRUCTIVE to the adapter's state -- call it only after all
    observation encoding is done (the state is discarded after the example
    anyway). Exercises the engine's own validator plus the full
    scoring/joker path, i.e. the exact code path `HandPlayGymEnv` runs
    during PPO.

    Raises `GenerationError` on any failure -- per the pipeline's design,
    the worker logs it to failures.jsonl and skips the example.
    """
    gs = state.raw_state
    cr = gs.get("current_round", {})
    hand_size = len(gs.get("hand", []))
    if action_type not in (ActionType.PlayHand, ActionType.Discard):
        raise GenerationError(f"unknown action_type={action_type}")
    if not 1 <= len(selected_indices) <= MAX_LABEL_CARDS:
        raise GenerationError("label must select 1-5 cards")
    if selected_indices != sorted(selected_indices) or len(set(selected_indices)) != len(
        selected_indices
    ):
        raise GenerationError("label indices must be unique and sorted ascending")
    if any(index < 0 or index >= hand_size for index in selected_indices):
        raise GenerationError(
            f"label indices {selected_indices} outside actual hand length {hand_size}"
        )
    if action_type == ActionType.PlayHand and cr.get("hands_left", 0) < 1:
        raise GenerationError("PlayHand label is illegal with no hands left")
    if action_type == ActionType.Discard and cr.get("discards_left", 0) < 1:
        raise GenerationError("Discard label is illegal with no discards left")

    indices = tuple(selected_indices)
    engine_action = (
        EnginePlayHand(card_indices=indices)
        if action_type == ActionType.PlayHand
        else EngineDiscard(card_indices=indices)
    )
    try:
        state.step(engine_action)
    except Exception as exc:
        raise GenerationError(f"label failed engine execution: {exc}") from exc


def generate_one_example(seed: str, config: HandPlayConfig) -> Example:
    """Sample one domain-randomized hand-play state via `HandPlayAdapter`
    and label it with the exact P(clear)-not-EV solver. Raises
    `GenerationError` (or lets a solver exception propagate) on any
    failure -- callers must catch and log, not swallow silently.
    """
    adapter = HandPlayAdapter(config)
    adapter.reset(BACK_KEY, STAKE, seed)
    return label_and_encode(adapter, seed)


def generate_one_example_from_blob(blob: bytes, record_id: str) -> Example:
    """Label one HARVESTED state (C2): restore the blob, then run the exact
    same solve/encode body stages 1-4 use.

    `record_id` doubles as the `mc_seed`, so a harvested label is byte-
    reproducible across machines. It is the record id -- NOT the run seed --
    because two records from one run must not share MC draws (pitfall #6).

    Restoration goes through `harvest_restore.restore_state`, which repairs
    known capture skew; unpickling the blob directly here would label states
    under an engine bug that no longer exists.
    """
    from harvest_restore import restore_state

    return label_and_encode(RestoredHarvestState(restore_state(blob)), record_id)


def label_and_encode(state: HandTurnState, seed: str) -> Example:
    """Solve, label and encode one hand-turn state, whatever produced it.

    THE single labeling path: stages 1-4 reach it with a freshly sampled
    `HandPlayAdapter` state, stage 5 with a restored harvest blob. `seed`
    threads into the solver as `mc_seed` and is stored on the Example.
    """
    gs = state.raw_state

    hand: list = gs["hand"]
    jokers: list = gs["jokers"]
    hand_levels = gs["hand_levels"]
    blind = gs["blind"]
    rng = gs["rng"]
    cr = gs["current_round"]

    hands_left = cr.get("hands_left", 0)
    discards_left = cr.get("discards_left", 0)
    blind_chips = getattr(blind, "chips", 0) if blind else 0
    chips_needed = max(0.0, blind_chips - gs.get("chips", 0))

    deck = DeckComposition.from_deck(gs.get("deck", []))
    flags = get_hand_eval_flags(jokers)

    choice = solve_hand_for_ante_clear(
        hand,
        jokers,
        hand_levels,
        blind,
        rng,
        deck,
        chips_needed,
        hands_left,
        discards_left,
        game_state=gs,
        blind_chips=blind_chips,
        four_fingers=flags["four_fingers"],
        shortcut=flags["shortcut"],
        mc_seed=seed,  # makes the future-hand MC draws (and p_clear) reproducible
    )

    acted_cards = acted_cards_from_choice(choice)
    selected_indices = sorted(indices_by_identity(acted_cards, hand))

    action_type = ActionType.PlayHand if choice.action == "play" else ActionType.Discard

    # Dual counter, matching build_observation_v2: a GENUINE overfill
    # (non-negative jokers exceeding joker_slots) is a Riff-raff-class engine
    # bug and stays loud; a legal wide/negative build (negatives don't consume
    # a slot) is ENCODED, not dropped. Without this the harvest labeler would
    # raise GenerationError on every >5-joker state and silently skip it to
    # failures.jsonl -- exactly the negative/wide builds the h1 model should
    # value.
    _check_joker_overfill(gs, jokers)
    ent = encode_hand_state_v2(gs)

    # Hand rows deliberately stay actual-width. write_shard pads each shard
    # only to its widest example, then the loader up-pads to the obs width.
    # Jokers/consumables truncate their tail past the fixed v2 width (harvested
    # full-run states can exceed it via negative editions -- Negative jokers
    # for the joker block, Perkeo copies for the consumable block); truncation
    # is lowest-slot-first as a pure safety valve, same policy as
    # build_observation_v2.
    joker_padded, joker_mask = _pad_entities(
        ent["jokers"][:MAX_JOKERS_V2], MAX_JOKERS_V2, D_JOKER
    )
    cons_padded, cons_mask = _pad_entities(
        ent["consumables"][:MAX_CONSUMABLES_V2], MAX_CONSUMABLES_V2, D_CONSUMABLE
    )
    trigger = np.zeros((len(hand), MAX_JOKERS_V2, 2), dtype=bool)
    trigger_src = ent["trigger_match"][:, :MAX_JOKERS_V2]
    trigger[: trigger_src.shape[0], : trigger_src.shape[1]] = trigger_src

    # Must come AFTER encoding: tier 2 executes the action on the real
    # state, mutating it (the state is discarded after this function).
    validate_label_executability(state, action_type, selected_indices)

    return Example(
        global_context=ent["global_context"],
        hand_cards=ent["hand_cards"],
        hand_mask=np.ones(len(hand), dtype=bool),
        jokers=joker_padded,
        joker_mask=joker_mask,
        joker_ids=_pad_1d(ent["joker_ids"], MAX_JOKERS_V2, np.int64),
        copy_active=_pad_1d(ent["copy_active"], MAX_JOKERS_V2, np.float32),
        copy_target_ids=_pad_1d(ent["copy_target_ids"], MAX_JOKERS_V2, np.int64),
        trigger_match=trigger,
        consumables=cons_padded,
        consumable_mask=cons_mask,
        action_type=int(action_type),
        card_indices=np.pad(
            np.asarray(selected_indices, dtype=np.int64),
            (0, MAX_LABEL_CARDS - len(selected_indices)),
            constant_values=-1,
        ),
        p_clear=float(choice.p_clear),
        seed=seed,
    )


def write_shard(path: Path, examples: list[Example]) -> None:
    """Write one `.npz` shard. `schema_version` lets a future consumer
    detect stale data if `observation.py`'s encoding shape ever changes.

    The consumable block stores the REAL owned consumables (empty for
    stages 1-4, genuinely populated for harvested C2 states) while the
    LABELS stay consumable-blind: the solver ignores consumables entirely,
    so `p_clear`/action labels are computed as if the block were empty. BC
    just learns an input that is inert for hand-play -- deliberately, so
    h2's BC pool doesn't show zeros where live play shows real consumables
    (in-blind consumable SELECTION itself stays at h2; see
    docs/pre-regen-handoff.md, B2 slice 4 rider).
    """
    hand_width = max(example.hand_cards.shape[0] for example in examples)

    def pad_hand_axis(arr: np.ndarray) -> np.ndarray:
        padded = np.zeros((hand_width, *arr.shape[1:]), dtype=arr.dtype)
        padded[: arr.shape[0]] = arr
        return padded

    np.savez_compressed(
        path,
        schema_version=np.array([SCHEMA_VERSION]),
        global_context=np.stack([e.global_context for e in examples]),
        hand_cards=np.stack([pad_hand_axis(e.hand_cards) for e in examples]),
        hand_mask=np.stack([pad_hand_axis(e.hand_mask) for e in examples]),
        jokers=np.stack([e.jokers for e in examples]),
        joker_mask=np.stack([e.joker_mask for e in examples]),
        joker_ids=np.stack([e.joker_ids for e in examples]),
        copy_active=np.stack([e.copy_active for e in examples]),
        copy_target_ids=np.stack([e.copy_target_ids for e in examples]),
        trigger_match=np.stack([pad_hand_axis(e.trigger_match) for e in examples]),
        consumables=np.stack([e.consumables for e in examples]),
        consumable_mask=np.stack([e.consumable_mask for e in examples]),
        action_type=np.array([e.action_type for e in examples], dtype=np.int64),
        card_indices=np.stack([e.card_indices for e in examples]),
        p_clear=np.array([e.p_clear for e in examples], dtype=np.float32),
        seed=np.array([e.seed for e in examples]),
    )


def _resume_point(
    output_dir: Path, worker_id: int, start_idx: int, end_idx: int
) -> tuple[int, int]:
    """Scan this worker's existing shards and return (resume_idx, next_shard_idx).

    Each stored example's seed string ends in its global index, so an
    interrupted run can be relaunched with the SAME stage/total/num-workers
    settings and each worker continues after the highest index it already
    wrote (killing a run only ever costs the current in-memory buffer).
    Seeds outside this worker's [start_idx, end_idx) range are ignored —
    they'd mean the partitioning changed, in which case shard files no
    longer correspond to ranges and resuming would silently skip or
    duplicate work. Failed (skipped) indices before the resume point are
    already in the failures log and are not retried.
    """
    resume_idx = start_idx
    shard_paths = sorted(output_dir.glob(f"worker_{worker_id:03d}_shard_*.npz"))
    for shard_path in shard_paths:
        seeds = np.load(shard_path)["seed"]
        for seed in seeds:
            idx = int(str(seed).rsplit("_", 1)[-1])
            if start_idx <= idx < end_idx:
                resume_idx = max(resume_idx, idx + 1)
    return resume_idx, len(shard_paths)


def _worker_run(
    worker_id: int,
    start_idx: int,
    end_idx: int,
    stage_name: str,
    config: HandPlayConfig,
    output_dir: Path,
    shard_size: int,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    failures_path = output_dir / f"worker_{worker_id:03d}_failures.jsonl"

    resume_idx, shard_idx = _resume_point(output_dir, worker_id, start_idx, end_idx)

    buffer: list[Example] = []

    def flush() -> None:
        nonlocal shard_idx
        if not buffer:
            return
        shard_path = output_dir / f"worker_{worker_id:03d}_shard_{shard_idx:05d}.npz"
        write_shard(shard_path, buffer)
        shard_idx += 1
        buffer.clear()

    with open(failures_path, "a", encoding="utf-8") as failures_file:
        for global_idx in range(resume_idx, end_idx):
            seed = f"{stage_name}_{global_idx:08d}"
            try:
                example = generate_one_example(seed, config)
            except Exception as exc:  # noqa: BLE001 -- one bad sample must not kill the worker
                failures_file.write(
                    json.dumps(
                        {
                            "seed": seed,
                            "error": str(exc),
                            "traceback": traceback.format_exc(),
                        }
                    )
                    + "\n"
                )
                failures_file.flush()
                continue
            buffer.append(example)
            if len(buffer) >= shard_size:
                flush()
        flush()


def partition_indices(total: int, num_workers: int) -> list[tuple[int, int]]:
    """Split [0, total) into up to `num_workers` contiguous, non-overlapping
    (start, end) ranges covering every index exactly once. The range
    boundaries depend only on (total, num_workers) -- not on wall-clock
    scheduling -- which is what makes the seed set reproducible.
    """
    if total <= 0 or num_workers <= 0:
        return []
    chunk = -(-total // num_workers)  # ceil division
    ranges = []
    for worker_id in range(num_workers):
        start_idx = worker_id * chunk
        end_idx = min(start_idx + chunk, total)
        if start_idx >= end_idx:
            break
        ranges.append((start_idx, end_idx))
    return ranges


def run_generation_job(job: GenerationJobConfig) -> None:
    """Top-level entry point: partitions [0, total_examples) into fixed
    per-worker index ranges and spawns one independent process per worker.
    Each worker writes its own shards and failures file -- no results are
    passed back through this process.
    """
    job.output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "stage_name": job.stage_name,
        "schema_version": SCHEMA_VERSION,
        "total_examples": job.total_examples,
        "num_workers": job.num_workers,
        "shard_size": job.shard_size,
        "back_key": BACK_KEY,
        "stake": STAKE,
        "hand_play_config": asdict(job.hand_play_config),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    with open(job.output_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    processes = []
    for worker_id, (start_idx, end_idx) in enumerate(
        partition_indices(job.total_examples, job.num_workers)
    ):
        p = multiprocessing.Process(
            target=_worker_run,
            args=(
                worker_id,
                start_idx,
                end_idx,
                job.stage_name,
                job.hand_play_config,
                job.output_dir,
                job.shard_size,
            ),
        )
        p.start()
        processes.append(p)

    for p in processes:
        p.join()


# ---------------------------------------------------------------------------
# C2: snapshot-fed labeling front-end (the harvested BC stage)
# ---------------------------------------------------------------------------
#
# Stages 1-4 SAMPLE synthetic states; this mode LABELS real ones. The states
# come from the C1 manifest over the phase-1 harvest corpus, and everything
# downstream of `gs` -- solver, encoder, both validation tiers, shard writer --
# is shared with stages 1-4 by construction (see `label_and_encode`).

HARVEST_STAGE_NAME = "stage5_harvested"

# Stop-and-investigate threshold for the run's failure rate. A silently thinned
# stage is worse than a loud stop: the whole point of the harvest is the states
# it contains, and a systematic failure (a bad restore, a schema slip) would
# preferentially eat exactly the unusual states worth having.
DEFAULT_MAX_FAILURE_RATE = 0.03


@dataclass
class HarvestJobConfig:
    manifest_path: Path
    blob_dir: Path
    output_dir: Path
    num_workers: int
    stage_name: str = HARVEST_STAGE_NAME
    shard_size: int = 500
    allow_sha_mismatch: bool = False
    max_failure_rate: float = DEFAULT_MAX_FAILURE_RATE


class BlobStore:
    """Reads per-run blob shards (`blobs/{run_seed}.pkl`), caching recent ones.

    One shard holds every record of one run, so labeling a worker's slice in
    run order costs one read per run rather than one per record. Workers sort
    their slice for exactly that reason (the manifest itself stays shuffled so
    slow deep-ante states spread across workers).
    """

    def __init__(self, blob_dir: Path, cache_size: int = 2) -> None:
        self._blob_dir = Path(blob_dir)
        self._cache_size = max(1, cache_size)
        self._cache: dict[str, dict[str, bytes]] = {}
        self._order: list[str] = []

    def _shard(self, run_seed: str) -> dict[str, bytes]:
        if run_seed in self._cache:
            return self._cache[run_seed]
        path = self._blob_dir / f"{run_seed}.pkl"
        if not path.exists():
            raise GenerationError(f"blob shard missing for run {run_seed!r}: {path}")
        with path.open("rb") as fh:
            shard = pickle.load(fh)
        self._cache[run_seed] = shard
        self._order.append(run_seed)
        while len(self._order) > self._cache_size:
            self._cache.pop(self._order.pop(0), None)
        return shard

    def get(self, run_seed: str, record_id: str) -> bytes:
        shard = self._shard(run_seed)
        if record_id not in shard:
            raise GenerationError(f"record {record_id!r} not in blob shard for {run_seed!r}")
        return shard[record_id]


def load_selection_manifest(path: Path) -> dict[str, Any]:
    """Load a C1 manifest, rejecting a shape this labeler doesn't understand."""
    with open(path, encoding="utf-8") as fh:
        manifest = json.load(fh)
    if manifest.get("manifest_version") != 1:
        raise GenerationError(
            f"{path}: unsupported manifest_version {manifest.get('manifest_version')!r}"
        )
    records = manifest.get("records")
    if not records:
        raise GenerationError(f"{path}: manifest has no records")
    return manifest


def check_corpus_sha(records: list[dict[str, Any]], *, allow_mismatch: bool) -> dict[str, Any]:
    """Compare each record's capture sha against the current checkout (pitfall #7).

    Blobs are pickles of live engine objects, so an engine change between
    capture and labeling can break restoration -- or, worse, restore fine while
    behaviour has drifted. This gate exists so that decision is always EXPLICIT:
    re-harvest, or accept and document. It never silently proceeds.

    Known and accepted for the h1 regen: `data/harvest_s0` was captured at
    57f1088 on the 9600X (a commit that isn't in this repo, so the mismatch
    cannot be diffed here -- only reported). The skew was analysed and the one
    behaviour-affecting difference, The Idol's uncached `id`, is repaired
    exactly on restore; see `harvest_restore.py`. So the h1 regen is expected to
    pass `--allow-sha-mismatch`.
    """
    from harvest_s0_rollouts import git_sha  # lazy: parent process only

    current = git_sha()
    counts = Counter(str(r.get("git_sha", "unknown")) for r in records)
    mismatched = {sha: n for sha, n in counts.items() if sha != current}
    report = {
        "current_sha": current,
        "record_shas": dict(sorted(counts.items())),
        "n_mismatched": sum(mismatched.values()),
        "allowed": allow_mismatch,
    }
    if not mismatched:
        return report

    detail = ", ".join(f"{sha[:10]} x{n}" for sha, n in sorted(mismatched.items()))
    if not allow_mismatch:
        raise GenerationError(
            f"{sum(mismatched.values())}/{len(records)} records were captured at a "
            f"different engine sha than this checkout ({current[:10]}): {detail}. "
            "Blobs are pickles of live engine objects, so labeling them here may be "
            "wrong in ways that load cleanly. Re-harvest, or pass "
            "--allow-sha-mismatch to accept the skew explicitly."
        )
    print(
        f"[c2] WARNING: engine-version skew ACCEPTED via --allow-sha-mismatch. "
        f"checkout={current[:10]} corpus={detail}. Known skew (The Idol's uncached "
        f"id) is repaired on restore; see harvest_restore.py."
    )
    return report


def _completed_record_ids(output_dir: Path, worker_id: int) -> tuple[set[str], int]:
    """Which records this worker already wrote, and its next shard index.

    Resume is by record-id MEMBERSHIP, not by parsing an index out of the seed
    the way the stage 1-4 path does: a harvested seed is a `record_id` whose
    trailing number is a turn index, so index-parsing would silently resume at
    the wrong place.
    """
    done: set[str] = set()
    shard_paths = sorted(output_dir.glob(f"worker_{worker_id:03d}_shard_*.npz"))
    for shard_path in shard_paths:
        done.update(str(seed) for seed in np.load(shard_path)["seed"])
    return done, len(shard_paths)


def _harvest_worker_run(
    worker_id: int,
    records: list[dict[str, Any]],
    blob_dir: Path,
    output_dir: Path,
    shard_size: int,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    failures_path = output_dir / f"worker_{worker_id:03d}_failures.jsonl"

    done, shard_idx = _completed_record_ids(output_dir, worker_id)
    store = BlobStore(blob_dir)
    todo = [r for r in records if str(r["record_id"]) not in done]
    # Blob locality: one shard read per run instead of one per record.
    todo.sort(key=lambda r: (str(r["run_seed"]), str(r["record_id"])))

    error_counts: Counter = Counter()
    buffer: list[Example] = []

    def flush() -> None:
        nonlocal shard_idx
        if not buffer:
            return
        write_shard(output_dir / f"worker_{worker_id:03d}_shard_{shard_idx:05d}.npz", buffer)
        shard_idx += 1
        buffer.clear()

    with open(failures_path, "a", encoding="utf-8") as failures_file:
        for record in todo:
            record_id = str(record["record_id"])
            try:
                blob = store.get(str(record["run_seed"]), record_id)
                example = generate_one_example_from_blob(blob, record_id)
            except Exception as exc:  # noqa: BLE001 -- one bad record must not kill the worker
                # Tag every failure by kind and surface it as it happens.
                # A skipped record is invisible otherwise, and the failures
                # that matter here are SYSTEMATIC (a bad restore, a schema
                # slip): those eat a whole class of states, so the tag
                # breakdown is what distinguishes "a few odd hands" from
                # "the harvest is quietly broken".
                error_type = type(exc).__name__
                error_counts[error_type] += 1
                failures_file.write(
                    json.dumps(
                        {
                            "seed": record_id,
                            "run_seed": record.get("run_seed"),
                            "error_type": error_type,
                            "error": str(exc),
                            "traceback": traceback.format_exc(),
                        }
                    )
                    + "\n"
                )
                failures_file.flush()
                print(
                    f"[c2][worker {worker_id:03d}] FAILED {record_id}: {error_type}: {exc} "
                    f"(this worker: {error_counts[error_type]}x {error_type}, "
                    f"{sum(error_counts.values())}/{len(todo)} failed)",
                    file=sys.stderr,
                    flush=True,
                )
                continue
            buffer.append(example)
            if len(buffer) >= shard_size:
                flush()
        flush()


def summarize_run(output_dir: Path, n_requested: int) -> dict[str, Any]:
    """Count what actually landed, so a thinned stage can't ship unnoticed.

    `errors_by_type` is the diagnostic that matters: a handful of assorted
    failures is noise, but a large count under ONE tag means a systematic
    fault, and systematic faults eat a whole CLASS of states (exactly the
    unusual ones the harvest exists for) rather than a random sample.
    """
    n_written = 0
    for shard_path in sorted(output_dir.glob("worker_*_shard_*.npz")):
        n_written += len(np.load(shard_path)["seed"])

    n_failed = 0
    errors_by_type: Counter = Counter()
    for failures_path in sorted(output_dir.glob("worker_*_failures.jsonl")):
        with open(failures_path, encoding="utf-8") as fh:
            for line in fh:
                if not line.strip():
                    continue
                n_failed += 1
                try:
                    errors_by_type[str(json.loads(line).get("error_type", "unknown"))] += 1
                except json.JSONDecodeError:
                    errors_by_type["unparseable_failure_row"] += 1

    return {
        "n_requested": n_requested,
        "n_written": n_written,
        "n_failed": n_failed,
        "failure_rate": round(n_failed / n_requested, 4) if n_requested else 0.0,
        "errors_by_type": dict(sorted(errors_by_type.items(), key=lambda kv: (-kv[1], kv[0]))),
    }


def run_harvest_job(job: HarvestJobConfig) -> dict[str, Any]:
    """Label the C1 manifest's records into a shard stage (C2's entry point)."""
    manifest = load_selection_manifest(job.manifest_path)
    records: list[dict[str, Any]] = manifest["records"]
    sha_report = check_corpus_sha(records, allow_mismatch=job.allow_sha_mismatch)

    job.output_dir.mkdir(parents=True, exist_ok=True)
    # num_workers is RECORDED, not just used: resume partitioning is fixed by
    # (record list, num_workers), and the 2026-07-05 incident was a transferred
    # partial run silently re-partitioning under a different default (925
    # duplicated + 321 missing examples).
    job_manifest = {
        "stage_name": job.stage_name,
        "schema_version": SCHEMA_VERSION,
        "source": "harvested",
        "selection_manifest": job.manifest_path.as_posix(),
        "selection_manifest_params": manifest.get("params"),
        "blob_dir": job.blob_dir.as_posix(),
        "n_records": len(records),
        "num_workers": job.num_workers,
        "shard_size": job.shard_size,
        "engine_sha": sha_report,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    with open(job.output_dir / "manifest.json", "w", encoding="utf-8") as fh:
        json.dump(job_manifest, fh, indent=2)

    processes = []
    for worker_id, (start_idx, end_idx) in enumerate(
        partition_indices(len(records), job.num_workers)
    ):
        p = multiprocessing.Process(
            target=_harvest_worker_run,
            args=(
                worker_id,
                records[start_idx:end_idx],
                job.blob_dir,
                job.output_dir,
                job.shard_size,
            ),
        )
        p.start()
        processes.append(p)
    for p in processes:
        p.join()

    summary = summarize_run(job.output_dir, len(records))
    if summary["n_failed"]:
        breakdown = ", ".join(f"{n}x {tag}" for tag, n in summary["errors_by_type"].items())
        print(
            f"[c2] {summary['n_failed']}/{summary['n_requested']} records failed "
            f"({summary['failure_rate']:.2%}): {breakdown}. Details in "
            f"{job.output_dir}/worker_*_failures.jsonl"
        )
    if summary["failure_rate"] > job.max_failure_rate:
        breakdown = ", ".join(f"{n}x {tag}" for tag, n in summary["errors_by_type"].items())
        raise GenerationError(
            f"{summary['n_failed']}/{summary['n_requested']} records failed "
            f"({summary['failure_rate']:.1%} > {job.max_failure_rate:.1%}): {breakdown}. "
            "Stage may be systematically thinned -- inspect worker_*_failures.jsonl "
            "before consuming it."
        )
    return summary


def _parse_int_range(spec: str) -> tuple[int, int]:
    lo, hi = spec.split(",")
    return (int(lo), int(hi))


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stage",
        choices=sorted(stage_presets()),
        help="Use a named curriculum-stage preset (config + example count). "
        "Explicit flags below override individual preset fields.",
    )
    harvest = parser.add_argument_group(
        "harvested stage (C2)",
        "Label real mid-run states selected by a C1 manifest instead of sampling "
        "domain-randomized ones. --manifest switches the script into this mode; the "
        "stage-preset/config flags do not apply to it.",
    )
    harvest.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="C1 selection manifest (e.g. manifests/h1_harvested.json)",
    )
    harvest.add_argument(
        "--blob-dir",
        type=Path,
        default=Path("data/harvest_s0/blobs"),
        help="per-run blob shards from the phase-1 harvest",
    )
    harvest.add_argument(
        "--allow-sha-mismatch",
        action="store_true",
        help="accept records captured at a different engine sha (logs loudly). "
        "Required for the h1 corpus -- see check_corpus_sha.",
    )
    harvest.add_argument(
        "--max-failure-rate",
        type=float,
        default=DEFAULT_MAX_FAILURE_RATE,
        help="fail the run rather than ship a silently thinned stage",
    )
    parser.add_argument("--stage-name", help="Dataset/seed-prefix name; defaults to --stage")
    parser.add_argument("--total-examples", type=int, help="Required unless --stage is given")
    parser.add_argument(
        "--num-workers", type=int, default=max(1, (multiprocessing.cpu_count() or 2) - 1)
    )
    parser.add_argument("--output-dir", type=Path, default=Path("data/hand_agent_demos"))
    parser.add_argument("--shard-size", type=int, default=500)
    parser.add_argument("--ante-range", type=_parse_int_range, default=None)
    parser.add_argument("--hands-range", type=_parse_int_range, default=None)
    parser.add_argument("--discards-range", type=_parse_int_range, default=None)
    parser.add_argument("--dollars-range", type=_parse_int_range, default=None)
    parser.add_argument(
        "--dollar-marginals",
        type=Path,
        default=None,
        help="harvest reductions.json (or bare ante->dollars->count mapping); "
        "enables harvested-marginal money sampling with a flat tail "
        "(the h1 stages 1-4 regen config)",
    )
    parser.add_argument(
        "--dollar-tail-prob",
        type=float,
        default=None,
        help="flat-tail probability when --dollar-marginals is set (config default 0.2)",
    )
    parser.add_argument("--hand-size-tail-prob", type=float, default=None)
    parser.add_argument("--hand-size-delta-range", type=_parse_int_range, default=None)
    parser.add_argument("--blind-stages", default=None)
    parser.add_argument("--joker-pool", default=None, help="comma-separated joker keys")
    parser.add_argument("--joker-count-range", type=_parse_int_range, default=None)
    args = parser.parse_args()

    if args.manifest is not None:
        stage_name = args.stage_name or HARVEST_STAGE_NAME
        summary = run_harvest_job(
            HarvestJobConfig(
                manifest_path=args.manifest,
                blob_dir=args.blob_dir,
                output_dir=args.output_dir / stage_name,
                num_workers=args.num_workers,
                stage_name=stage_name,
                shard_size=args.shard_size,
                allow_sha_mismatch=args.allow_sha_mismatch,
                max_failure_rate=args.max_failure_rate,
            )
        )
        print(f"[c2] {json.dumps(summary)}")
        return

    if args.stage:
        preset = stage_presets()[args.stage]
        config = preset.config
        stage_name = args.stage_name or args.stage
        total_examples = args.total_examples or preset.total_examples
    else:
        if not args.stage_name or not args.total_examples:
            parser.error("--stage-name and --total-examples are required without --stage")
        config = HandPlayConfig()
        stage_name = args.stage_name
        total_examples = args.total_examples

    overrides: dict[str, Any] = {}
    if args.ante_range is not None:
        overrides["ante_range"] = args.ante_range
    if args.hands_range is not None:
        overrides["hands_range"] = args.hands_range
    if args.discards_range is not None:
        overrides["discards_range"] = args.discards_range
    if args.dollars_range is not None:
        overrides["dollars_range"] = args.dollars_range
    if args.dollar_marginals is not None:
        overrides["dollar_marginals"] = load_dollar_marginals(args.dollar_marginals)
    if args.dollar_tail_prob is not None:
        overrides["dollar_flat_tail_prob"] = args.dollar_tail_prob
    if args.hand_size_tail_prob is not None:
        overrides["hand_size_tail_prob"] = args.hand_size_tail_prob
    if args.hand_size_delta_range is not None:
        overrides["hand_size_delta_range"] = args.hand_size_delta_range
    if args.blind_stages is not None:
        overrides["blind_stages"] = tuple(args.blind_stages.split(","))
    if args.joker_pool is not None:
        overrides["joker_pool"] = tuple(k for k in args.joker_pool.split(",") if k)
    if args.joker_count_range is not None:
        overrides["joker_count_range"] = args.joker_count_range
        overrides["joker_count_bands"] = None  # explicit range disables preset bands
    if overrides:
        config = replace(config, **overrides)

    job = GenerationJobConfig(
        stage_name=stage_name,
        hand_play_config=config,
        total_examples=total_examples,
        num_workers=args.num_workers,
        output_dir=args.output_dir / stage_name,
        shard_size=args.shard_size,
    )
    run_generation_job(job)


if __name__ == "__main__":
    main()
