"""Offline demonstration-generation pipeline for hand-agent BC.

Samples domain-randomized hand-play states via `HandPlayAdapter`, labels
each with `hand_solver.solve_hand_for_ante_clear` (the P(clear)-not-EV
oracle -- see CLAUDE.md "Ante-play (hand/discard) track" for why raw EV is
the wrong objective here), and writes padded `.npz` shards for
behavior-cloning training.

Design decided in a /grilling session (see CLAUDE.md open items):
  - Run once per curriculum stage: pass a `HandPlayConfig` + `stage_name`,
    get one dataset in `{output_dir}/{stage_name}/`. Don't mix stages into
    one pool -- BC training consumes stages as separable units.
  - Workers write their own `.npz` shards independently. No centralized
    collector -- avoids a serialization bottleneck and single point of
    failure for a run that's ~12s/example even after the permutation-search
    speed fix.
  - Seeds are `f"{stage_name}_{global_index:08d}"`, partitioned into fixed
    per-worker index ranges. The seed *set* depends only on
    (stage_name, total_examples), not on how many workers happen to run the
    job -- reruns with a different --num-workers still reproduce the same
    dataset.
  - A solver exception on one sampled state is logged to
    `{stage_dir}/worker_{id}_failures.jsonl` (seed + traceback) and skipped,
    not fatal to the whole run -- deterministic seeding makes a later
    retry-only-failures pass possible once the underlying bug is fixed.
  - Card selection labels are stored as a multi-hot mask over the padded
    hand width (matching `ActionMask.card_mask` in `action_space.py`), not
    as raw variable-length index tuples.
"""

from __future__ import annotations

import json
import multiprocessing
import sys
import time
import traceback
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any

import numpy as np

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

_REPO_ROOT = _SCRIPTS_DIR.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from hand_solver import AnteClearChoice, DeckComposition, solve_hand_for_ante_clear  # noqa: E402

from jackdaw.agents.hand_action_space import (  # noqa: E402
    combo_to_action,
    legal_action_mask,
)
from jackdaw.engine.actions import Discard as EngineDiscard  # noqa: E402
from jackdaw.engine.actions import PlayHand as EnginePlayHand  # noqa: E402
from jackdaw.engine.hand_eval import get_hand_eval_flags  # noqa: E402
from jackdaw.env.action_space import ActionType  # noqa: E402
from jackdaw.env.hand_play_adapter import (  # noqa: E402
    HandPlayAdapter,
    HandPlayConfig,
    JokerCountBand,
)
from jackdaw.env.observation import (  # noqa: E402
    D_JOKER,
    D_PLAYING_CARD,
    encode_global_context,
    encode_jokers_batch,
    encode_playing_cards_batch,
)

SCHEMA_VERSION = 1
MAX_HAND_CARDS = 8
MAX_JOKERS = 5
BACK_KEY = "b_red"
STAKE = 1

# ---------------------------------------------------------------------------
# Curriculum stage presets
# ---------------------------------------------------------------------------
#
# One dataset per stage, generated by separate invocations (`--stage <name>`)
# — never one mixed pool. Checked into git so the exact generating
# distribution of any dataset is reproducible months later; CLI flags
# override individual fields when experimenting.

# Count-first weighted joker-count distribution (see JokerCountBand):
# 30% five-joker boards (ante 3+ only), tapering to 10% each for 0/1/2,
# with 0/1-joker states confined to antes 1-2 where they actually occur
# in real play.
DEFAULT_COUNT_BANDS: tuple[JokerCountBand, ...] = (
    JokerCountBand(count=0, weight=0.10, ante_range=(1, 2)),
    JokerCountBand(count=1, weight=0.10, ante_range=(1, 2)),
    JokerCountBand(count=2, weight=0.10),
    JokerCountBand(count=3, weight=0.20),
    JokerCountBand(count=4, weight=0.20),
    JokerCountBand(count=5, weight=0.30, ante_range=(3, 8)),
)

# Stage 2: archetype-spanning curated pool — jokers chosen because they
# visibly CHANGE the optimal play/discard decision, not because they're
# strong. Covers suit/rank/hand-type conditionals, hand-detection modifiers
# (Four Fingers/Shortcut/Splash), order-sensitive scoring (Photograph/
# Hanging Chad/Ancient), scaling accumulation (Ride the Bus/Wee), retrigger
# and held-in-hand effects, plus one decision-irrelevant baseline (Joker).
STAGE2_JOKER_POOL: tuple[str, ...] = (
    "j_joker",
    "j_greedy_joker",
    "j_lusty_joker",
    "j_even_steven",
    "j_odd_todd",
    "j_fibonacci",
    "j_scholar",
    "j_jolly",
    "j_sly",
    "j_crazy",
    "j_droll",
    "j_four_fingers",
    "j_shortcut",
    "j_splash",
    "j_photograph",
    "j_hanging_chad",
    "j_ride_the_bus",
    "j_wee",
    "j_hack",
    "j_raised_fist",
    "j_ancient",
)


def all_joker_keys() -> tuple[str, ...]:
    """Every joker key in the engine's centers.json (150 as of writing)."""
    centers_path = _REPO_ROOT / "jackdaw" / "engine" / "data" / "centers.json"
    with open(centers_path, encoding="utf-8") as f:
        centers = json.load(f)
    return tuple(sorted(k for k in centers if k.startswith("j_")))


@dataclass(frozen=True)
class StagePreset:
    config: HandPlayConfig
    total_examples: int


def stage_presets() -> dict[str, StagePreset]:
    """Named curriculum-stage presets (function, not constant, so the
    all-150 pool is only loaded when actually requested)."""
    return {
        # Pipeline/baseline validation: pure hand-strength play, no jokers.
        "stage1_no_jokers": StagePreset(
            config=HandPlayConfig(),
            total_examples=2_000,
        ),
        # ~4000 x 3.2 avg jokers / 21 pool ~= 610 appearances per joker.
        "stage2_curated": StagePreset(
            config=HandPlayConfig(
                joker_pool=STAGE2_JOKER_POOL,
                joker_count_bands=DEFAULT_COUNT_BANDS,
            ),
            total_examples=4_000,
        ),
        # ~20000 x 3.2 / 150 ~= 425 appearances per joker — marginal
        # embedding exposure, not combinatorial coverage (see CLAUDE.md:
        # BC is a warm start, PPO does the generalization).
        "stage3_full": StagePreset(
            config=HandPlayConfig(
                joker_pool=all_joker_keys(),
                joker_count_bands=DEFAULT_COUNT_BANDS,
            ),
            total_examples=20_000,
        ),
    }


class GenerationError(Exception):
    """Raised for a sampled state the pipeline can't turn into a valid
    label -- callers must catch this per-example, not let it kill a
    worker's whole index range."""


@dataclass
class GenerationJobConfig:
    stage_name: str
    hand_play_config: HandPlayConfig
    total_examples: int
    num_workers: int
    output_dir: Path
    shard_size: int = 500


@dataclass
class Example:
    global_context: np.ndarray
    hand_cards: np.ndarray
    hand_mask: np.ndarray
    jokers: np.ndarray
    joker_mask: np.ndarray
    action_type: int
    card_target_mask: np.ndarray
    p_clear: float
    seed: str


def _pad_entities(arr: np.ndarray, max_n: int, dim: int) -> tuple[np.ndarray, np.ndarray]:
    n = arr.shape[0]
    if n > max_n:
        raise GenerationError(f"entity count {n} exceeds max {max_n}")
    padded = np.zeros((max_n, dim), dtype=np.float32)
    mask = np.zeros(max_n, dtype=bool)
    if n > 0:
        padded[:n] = arr
        mask[:n] = True
    return padded, mask


def acted_cards_from_choice(choice: AnteClearChoice) -> list:
    """The cards the label's action actually operates on.

    NOT simply `choice.hold` -- `hold`/`discard` are named from the
    "keep vs. discard" framing of a *discard* decision. For `action=="play"`,
    `hold` is repurposed by `hand_solver.py` to mean "the subset chosen to
    play" (see `best_immediate_play`'s callers), not "cards kept in hand".
    Getting this backwards silently produces a Discard label for what the
    solver actually recommended as a Play, or vice versa.
    """
    if choice.action == "play":
        return choice.hold
    if choice.action == "discard":
        return choice.discard
    raise GenerationError(f"unknown solver action: {choice.action!r}")


def indices_by_identity(cards: list, hand: list) -> list[int]:
    """Map `cards` back to their positions in `hand` by object identity,
    not value equality. `Card` is a plain @dataclass (value-based `__eq__`),
    so an Erratic deck's duplicate-valued cards would otherwise collide
    under `in`/`.index()` -- see the /grilling session and the matching fix
    in `hand_solver.best_immediate_play`.
    """
    id_to_index = {id(c): i for i, c in enumerate(hand)}
    try:
        return [id_to_index[id(c)] for c in cards]
    except KeyError as exc:
        raise GenerationError(
            f"solver returned a card not present (by identity) in the original hand: {exc}"
        ) from exc


def validate_label_executability(
    adapter: HandPlayAdapter,
    action_type: int,
    selected_indices: list[int],
) -> None:
    """Two-tier guard that a label is executable in the real game. Added
    after the 5-card-discard-cap bug (see CLAUDE.md): 8.3% of the first
    stage-1 dataset labeled discards the engine rejects, and it wasn't
    caught until BC training consumed the shards. Cost is negligible
    against the 2-12s solver call (~10us mask check + ~0.5ms engine step).

    Tier 1: the label must map to a legal index in the canonical
    Discrete(436) action space (`jackdaw/agents/hand_action_space.py`) --
    the same check the BC loader repeats at training time.

    Tier 2: actually execute the action through the real engine. This is
    DESTRUCTIVE to the adapter's state -- call it only after all
    observation encoding is done (the state is discarded after the example
    anyway). Exercises the engine's own validator plus the full
    scoring/joker path, i.e. the exact code path `HandPlayGymEnv` runs
    during PPO.

    Raises `GenerationError` on any failure -- per the pipeline's design,
    the worker logs it to failures.jsonl and skips the example.
    """
    gs = adapter.raw_state
    cr = gs.get("current_round", {})
    mask = legal_action_mask(
        len(gs.get("hand", [])),
        cr.get("hands_left", 0),
        cr.get("discards_left", 0),
    )
    try:
        action_index = combo_to_action(action_type, tuple(selected_indices))
    except ValueError as exc:
        raise GenerationError(f"label is not a canonical action: {exc}") from exc
    if not mask[action_index]:
        raise GenerationError(
            f"label (action_type={action_type}, cards={selected_indices}) is illegal "
            f"under the canonical action mask (hand={len(gs.get('hand', []))}, "
            f"hands_left={cr.get('hands_left')}, discards_left={cr.get('discards_left')})"
        )

    indices = tuple(selected_indices)
    engine_action = (
        EnginePlayHand(card_indices=indices)
        if action_type == ActionType.PlayHand
        else EngineDiscard(card_indices=indices)
    )
    try:
        adapter.step(engine_action)
    except Exception as exc:
        raise GenerationError(f"label failed engine execution: {exc}") from exc


def generate_one_example(seed: str, config: HandPlayConfig) -> Example:
    """Sample one domain-randomized hand-play state via `HandPlayAdapter`
    and label it with the exact P(clear)-not-EV solver. Raises
    `GenerationError` (or lets a solver exception propagate) on any
    failure -- callers must catch and log, not swallow silently.
    """
    adapter = HandPlayAdapter(config)
    adapter.reset(BACK_KEY, STAKE, seed)
    gs = adapter.raw_state

    hand: list = gs["hand"]
    jokers: list = gs["jokers"]
    hand_levels = gs["hand_levels"]
    blind = gs["blind"]
    rng = gs["rng"]
    cr = gs["current_round"]

    hands_left = cr.get("hands_left", 0)
    discards_left = cr.get("discards_left", 0)
    blind_chips = getattr(blind, "chips", 0) if blind else 0
    chips_needed = max(0.0, blind_chips - gs.get("chips", 0))

    deck = DeckComposition.from_deck(gs.get("deck", []))
    flags = get_hand_eval_flags(jokers)

    choice = solve_hand_for_ante_clear(
        hand,
        jokers,
        hand_levels,
        blind,
        rng,
        deck,
        chips_needed,
        hands_left,
        discards_left,
        game_state=gs,
        blind_chips=blind_chips,
        four_fingers=flags["four_fingers"],
        shortcut=flags["shortcut"],
        mc_seed=seed,  # makes the future-hand MC draws (and p_clear) reproducible
    )

    acted_cards = acted_cards_from_choice(choice)
    selected_indices = indices_by_identity(acted_cards, hand)

    card_target_mask = np.zeros(MAX_HAND_CARDS, dtype=bool)
    for idx in selected_indices:
        if idx >= MAX_HAND_CARDS:
            raise GenerationError(f"hand index {idx} exceeds MAX_HAND_CARDS={MAX_HAND_CARDS}")
        card_target_mask[idx] = True

    action_type = ActionType.PlayHand if choice.action == "play" else ActionType.Discard

    global_ctx = encode_global_context(gs)
    hand_arr = encode_playing_cards_batch(hand, gs)
    joker_arr = encode_jokers_batch(jokers, gs)

    hand_padded, hand_mask = _pad_entities(hand_arr, MAX_HAND_CARDS, D_PLAYING_CARD)
    joker_padded, joker_mask = _pad_entities(joker_arr, MAX_JOKERS, D_JOKER)

    # Must come AFTER encoding: tier 2 executes the action on the real
    # state, mutating it (the state is discarded after this function).
    validate_label_executability(adapter, action_type, selected_indices)

    return Example(
        global_context=global_ctx,
        hand_cards=hand_padded,
        hand_mask=hand_mask,
        jokers=joker_padded,
        joker_mask=joker_mask,
        action_type=int(action_type),
        card_target_mask=card_target_mask,
        p_clear=float(choice.p_clear),
        seed=seed,
    )


def write_shard(path: Path, examples: list[Example]) -> None:
    """Write one `.npz` shard. `schema_version` lets a future consumer
    detect stale data if `observation.py`'s encoding shape ever changes."""
    np.savez_compressed(
        path,
        schema_version=np.array([SCHEMA_VERSION]),
        global_context=np.stack([e.global_context for e in examples]),
        hand_cards=np.stack([e.hand_cards for e in examples]),
        hand_mask=np.stack([e.hand_mask for e in examples]),
        jokers=np.stack([e.jokers for e in examples]),
        joker_mask=np.stack([e.joker_mask for e in examples]),
        action_type=np.array([e.action_type for e in examples], dtype=np.int64),
        card_target_mask=np.stack([e.card_target_mask for e in examples]),
        p_clear=np.array([e.p_clear for e in examples], dtype=np.float32),
        seed=np.array([e.seed for e in examples]),
    )


def _resume_point(
    output_dir: Path, worker_id: int, start_idx: int, end_idx: int
) -> tuple[int, int]:
    """Scan this worker's existing shards and return (resume_idx, next_shard_idx).

    Each stored example's seed string ends in its global index, so an
    interrupted run can be relaunched with the SAME stage/total/num-workers
    settings and each worker continues after the highest index it already
    wrote (killing a run only ever costs the current in-memory buffer).
    Seeds outside this worker's [start_idx, end_idx) range are ignored —
    they'd mean the partitioning changed, in which case shard files no
    longer correspond to ranges and resuming would silently skip or
    duplicate work. Failed (skipped) indices before the resume point are
    already in the failures log and are not retried.
    """
    resume_idx = start_idx
    shard_paths = sorted(output_dir.glob(f"worker_{worker_id:03d}_shard_*.npz"))
    for shard_path in shard_paths:
        seeds = np.load(shard_path)["seed"]
        for seed in seeds:
            idx = int(str(seed).rsplit("_", 1)[-1])
            if start_idx <= idx < end_idx:
                resume_idx = max(resume_idx, idx + 1)
    return resume_idx, len(shard_paths)


def _worker_run(
    worker_id: int,
    start_idx: int,
    end_idx: int,
    stage_name: str,
    config: HandPlayConfig,
    output_dir: Path,
    shard_size: int,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    failures_path = output_dir / f"worker_{worker_id:03d}_failures.jsonl"

    resume_idx, shard_idx = _resume_point(output_dir, worker_id, start_idx, end_idx)

    buffer: list[Example] = []

    def flush() -> None:
        nonlocal shard_idx
        if not buffer:
            return
        shard_path = output_dir / f"worker_{worker_id:03d}_shard_{shard_idx:05d}.npz"
        write_shard(shard_path, buffer)
        shard_idx += 1
        buffer.clear()

    with open(failures_path, "a", encoding="utf-8") as failures_file:
        for global_idx in range(resume_idx, end_idx):
            seed = f"{stage_name}_{global_idx:08d}"
            try:
                example = generate_one_example(seed, config)
            except Exception as exc:  # noqa: BLE001 -- one bad sample must not kill the worker
                failures_file.write(
                    json.dumps(
                        {
                            "seed": seed,
                            "error": str(exc),
                            "traceback": traceback.format_exc(),
                        }
                    )
                    + "\n"
                )
                failures_file.flush()
                continue
            buffer.append(example)
            if len(buffer) >= shard_size:
                flush()
        flush()


def partition_indices(total: int, num_workers: int) -> list[tuple[int, int]]:
    """Split [0, total) into up to `num_workers` contiguous, non-overlapping
    (start, end) ranges covering every index exactly once. The range
    boundaries depend only on (total, num_workers) -- not on wall-clock
    scheduling -- which is what makes the seed set reproducible.
    """
    if total <= 0 or num_workers <= 0:
        return []
    chunk = -(-total // num_workers)  # ceil division
    ranges = []
    for worker_id in range(num_workers):
        start_idx = worker_id * chunk
        end_idx = min(start_idx + chunk, total)
        if start_idx >= end_idx:
            break
        ranges.append((start_idx, end_idx))
    return ranges


def run_generation_job(job: GenerationJobConfig) -> None:
    """Top-level entry point: partitions [0, total_examples) into fixed
    per-worker index ranges and spawns one independent process per worker.
    Each worker writes its own shards and failures file -- no results are
    passed back through this process.
    """
    job.output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "stage_name": job.stage_name,
        "schema_version": SCHEMA_VERSION,
        "total_examples": job.total_examples,
        "num_workers": job.num_workers,
        "shard_size": job.shard_size,
        "back_key": BACK_KEY,
        "stake": STAKE,
        "hand_play_config": asdict(job.hand_play_config),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    with open(job.output_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    processes = []
    for worker_id, (start_idx, end_idx) in enumerate(
        partition_indices(job.total_examples, job.num_workers)
    ):
        p = multiprocessing.Process(
            target=_worker_run,
            args=(
                worker_id,
                start_idx,
                end_idx,
                job.stage_name,
                job.hand_play_config,
                job.output_dir,
                job.shard_size,
            ),
        )
        p.start()
        processes.append(p)

    for p in processes:
        p.join()


def _parse_int_range(spec: str) -> tuple[int, int]:
    lo, hi = spec.split(",")
    return (int(lo), int(hi))


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--stage",
        choices=sorted(stage_presets()),
        help="Use a named curriculum-stage preset (config + example count). "
        "Explicit flags below override individual preset fields.",
    )
    parser.add_argument("--stage-name", help="Dataset/seed-prefix name; defaults to --stage")
    parser.add_argument("--total-examples", type=int, help="Required unless --stage is given")
    parser.add_argument(
        "--num-workers", type=int, default=max(1, (multiprocessing.cpu_count() or 2) - 1)
    )
    parser.add_argument("--output-dir", type=Path, default=Path("data/hand_agent_demos"))
    parser.add_argument("--shard-size", type=int, default=500)
    parser.add_argument("--ante-range", type=_parse_int_range, default=None)
    parser.add_argument("--hands-range", type=_parse_int_range, default=None)
    parser.add_argument("--discards-range", type=_parse_int_range, default=None)
    parser.add_argument("--dollars-range", type=_parse_int_range, default=None)
    parser.add_argument("--blind-stages", default=None)
    parser.add_argument("--joker-pool", default=None, help="comma-separated joker keys")
    parser.add_argument("--joker-count-range", type=_parse_int_range, default=None)
    args = parser.parse_args()

    if args.stage:
        preset = stage_presets()[args.stage]
        config = preset.config
        stage_name = args.stage_name or args.stage
        total_examples = args.total_examples or preset.total_examples
    else:
        if not args.stage_name or not args.total_examples:
            parser.error("--stage-name and --total-examples are required without --stage")
        config = HandPlayConfig()
        stage_name = args.stage_name
        total_examples = args.total_examples

    overrides: dict[str, Any] = {}
    if args.ante_range is not None:
        overrides["ante_range"] = args.ante_range
    if args.hands_range is not None:
        overrides["hands_range"] = args.hands_range
    if args.discards_range is not None:
        overrides["discards_range"] = args.discards_range
    if args.dollars_range is not None:
        overrides["dollars_range"] = args.dollars_range
    if args.blind_stages is not None:
        overrides["blind_stages"] = tuple(args.blind_stages.split(","))
    if args.joker_pool is not None:
        overrides["joker_pool"] = tuple(k for k in args.joker_pool.split(",") if k)
    if args.joker_count_range is not None:
        overrides["joker_count_range"] = args.joker_count_range
        overrides["joker_count_bands"] = None  # explicit range disables preset bands
    if overrides:
        config = replace(config, **overrides)

    job = GenerationJobConfig(
        stage_name=stage_name,
        hand_play_config=config,
        total_examples=total_examples,
        num_workers=args.num_workers,
        output_dir=args.output_dir / stage_name,
        shard_size=args.shard_size,
    )
    run_generation_job(job)


if __name__ == "__main__":
    main()
